name: makepkg

on:
  schedule:
    - cron: '15 3 * * 0'

  push:
    branches: [ master ]
    paths:
      - 'makepkg/**'

  workflow_dispatch:

jobs:
  build_and_publish:
    name: Build [ makepkg ]
    uses: sfesenko/dockers/.github/workflows/build_and_publish.yml@master
    with:
      build_context: makepkg
